# Generated by Django 3.1.3 on 2020-11-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diploma', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requiredEducationLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requiredEducationLevel', to='diploma.diploma', verbose_name='diploma'),
        ),
    ]
