# Generated by Django 3.1.3 on 2020-11-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diploma', to='user.user', verbose_name='candidate'),
            preserve_default=False,
        ),
    ]
