# Generated by Django 3.1.3 on 2020-11-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20201119_2308'),
        ('user', '0002_diploma_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL, verbose_name='candidate'),
        ),
        migrations.DeleteModel(
            name='Diploma',
        ),
    ]
